name: Pages

on:
  repository_dispatch:
    types: [trigger-deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive

      - name: Clone latest posts
        env:
          GH_PAT: ${{ secrets.MY_TOKEN }}
        run: |
          rm -rf source/_posts
          git clone https://$GH_PAT@github.com/channinghsu/Blog-Post.git source/_posts

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy-zeabur:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Compress built files
          run: zip -r site.zip public

        - name: Deploy to Zeabur
          env:
            ZEABUR_API_KEY: ${{ secrets.ZEABUR_TOKEN }}
            PROJECT_ID: 66ab309eee5fff299348eda0
            SERVICE_ID: 66ab312eee5fff299348edaf
            ENVIRONMENT_ID: 66ab309e654859a82e0754bb
          run: |
            curl --request POST \
              --url https://gateway.zeabur.com/projects/$PROJECT_ID/services/$SERVICE_ID/deploy \
              --header "Authorization: Bearer $ZEABUR_API_KEY" \
              --header "Content-Type: application/json" \
              --data-binary @site.zip \
              --data '{"environment": "'$ENVIRONMENT_ID'"}'
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

