name: Pages

on:
  repository_dispatch:
    types: [trigger-deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPLOY_KEY }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive

      - name: Set Git Config
        run: |
          git config --global user.email "xu.baicheng@foxmail.com"
          git config --global user.name "Channing Hsu"

      - name: Update Submodules to Latest Commit
        run: |
          # Update submodules to ensure they are initialized
          git submodule update --init --recursive

          # Loop through each submodule and update
          git submodule foreach '
            echo "Updating submodule $path"
            git checkout main
            git fetch origin
            latest_commit=$(git rev-parse origin/main)
            echo "Latest commit in main branch: $latest_commit"
            git checkout $latest_commit
          '

          # Stage the changes in the main repository
          git add .

          # Commit the changes
          git commit -m "Update submodules to latest commit from main branch" || echo "No changes to commit"

          # Push the changes to the remote repository
          git push || echo "No changes to push"

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
